version: '3'
services:
  api:
    build:
      context: .
      target: builder
    container_name: outlookapi_container
    environment:
      username: "tesuto1125@outlook.com"
      password: "thanglol001"
      PORT: 42069
    ports:
      - '42069:42069'
    restart: "no"