version: '3'
services:
  api:
    build:
      context: .
      target: builder
    container_name: HTKT_AutoEmailing
    environment:
      username: "tuanna.vpi@pvu.edu.vn"
      password: "Tc@091712"
      PORT: 42069
    ports:
      - '42069:42069'
    restart: "no"